<?php

/**
 * BaseFacebook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $fb_id
 * @property boolean $activo
 * @property Usuario $Usuario
 * 
 * @method integer  getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer  getFbId()       Returns the current record's "fb_id" value
 * @method boolean  getActivo()     Returns the current record's "activo" value
 * @method Usuario  getUsuario()    Returns the current record's "Usuario" value
 * @method Facebook setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Facebook setFbId()       Sets the current record's "fb_id" value
 * @method Facebook setActivo()     Sets the current record's "activo" value
 * @method Facebook setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    scheduler
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacebook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('facebook');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fb_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));
    }
}