<?php

/**
 * CompartirTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompartirTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompartirTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Compartir');
    }
    public function getByIds($comparteId,$compartidoId)
    {
        return Doctrine_Query::create()
          ->select('*')
          ->from('Compartir')
          ->andWhere('comparte_id = ?', $comparteId)
          ->andWhere('compartido_id = ?', $compartidoId)
          ->fetchOne();
    }
}