<?php

/**
 * FacebookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacebookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacebookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Facebook');
    }
}