<?php

/**
 * UsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuario');
    }
    public function getUserByToken($token)
    {
        return Doctrine_Query::create()
          ->select('*')
          ->from('Usuario')
          ->andWhere('token = ?', $token)
          ->fetchOne();
    }
    public function getUserBySearchToken($token){
        
        return Doctrine_Query::create()
          ->select('*')
          ->from('Usuario')
          ->andWhere('search_token = ?', $token)
          ->fetchOne();
      
    }
    
    public static function usuariosByTag($tag){
        $resultados=array();
        $usuarios = Doctrine_Core::getTable("Usuario")
                ->createQuery('u')
                ->where("u.admin=false")
                
//                ->andWhere("u.nombres LIKE '%a%'")
                ->andWhere("lower(concat('u.nombres',' ','u.apellidos')) LIKE lower('%".$tag."%')")
                ->limit(30)
                ->execute();
      foreach($usuarios as $usuario){
          array_push($resultados, array("key" => '"'.$usuario->getToken().'"',"value" => $usuario->getApellidos()." ".$usuario->getNombres()));
          
      }
      return $resultados;
    }
}